#!/usr/bin/env python3
"""
Prompt logger — saves every LLM prompt for observability and external evaluation.

Two output directories:

  state/run_prompts/        — live prompts written during normal LLM runs.
                              One timestamped file per call; never wiped.

  state/generated_prompts/  — prompts generated by --build-prompts mode.
                              Wiped and refreshed on every --build-prompts run.
                              Uses a stable "draft" timestamp so file names are
                              deterministic across repeated builds.

File naming (same convention for both directories):
  {step}_{session_date}_{session_id}_{timestamp}_{model_safe}_{label}.txt

  step         : "session_topics" | "interventions"
  session_date : YYYY-MM-DD
  session_id   : e.g. 8856
  timestamp    : YYYYMMDDTHHMMSSz (UTC)  or "draft" for build-prompts mode
  model_safe   : model name with ':' replaced by '-'
  label        : e.g. "single_pass", "window_2of8", "reduce", "batch_1of3"

File contents:
  A plain-text file with a metadata header followed by the full system and
  user prompts, separated by clearly marked dividers.

Matching convention for external outputs:
  Place a file with the SAME name as a generated_prompts file under
  state/external_prompts_output/ and fill it with the raw JSON response from
  the external model.  The ingest step will parse it and store results to the
  DB exactly as if the local LLM had returned that response.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

PROMPTS_DIR = Path("state/run_prompts")
GENERATED_PROMPTS_DIR = Path("state/generated_prompts")
EXTERNAL_OUTPUTS_DIR = Path("state/external_prompts_output")


def _safe_model(model: str) -> str:
    """Replace characters that are invalid in filenames."""
    return re.sub(r"[:/\\]", "-", model)


def prompt_filename(
    *,
    step: str,
    session_date: str,
    session_id: str,
    model: str,
    label: str,
    timestamp: str | None = None,
) -> str:
    """
    Build the canonical filename for a prompt (without directory).

    Pass ``timestamp="draft"`` to get a stable, deterministic filename that is
    not tied to a specific run moment — useful for --build-prompts mode so the
    same file is overwritten on repeated calls rather than accumulating copies.
    If ``timestamp`` is None the current UTC time is used.
    """
    ts = timestamp if timestamp is not None else datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    model_safe = _safe_model(model)
    label_safe = re.sub(r"[^a-zA-Z0-9_\-]", "_", label)
    return f"{step}_{session_date}_{session_id}_{ts}_{model_safe}_{label_safe}.txt"


def save_prompt(
    *,
    step: str,
    session_id: str,
    session_date: str,
    model: str,
    label: str,
    system_prompt: str,
    user_message: str,
    extra_meta: dict | None = None,
    timestamp: str | None = None,
) -> Path:
    """
    Write the prompt to a file.

    ``timestamp`` controls the timestamp component of the filename and the
    output directory:
    - ``None`` (default): uses the current UTC time and writes to
      ``state/run_prompts/`` (normal production behaviour).
    - ``"draft"``: uses the literal string "draft" as the timestamp and writes
      to ``state/generated_prompts/`` (--build-prompts mode).  The directory is
      expected to have been wiped by the caller before the build run starts so
      that these files are always a complete, fresh snapshot.

    Returns the path of the written file.
    """
    ts = timestamp if timestamp is not None else datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    out_dir = GENERATED_PROMPTS_DIR if ts == "draft" else PROMPTS_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    filename = prompt_filename(
        step=step,
        session_date=session_date,
        session_id=session_id,
        model=model,
        label=label,
        timestamp=ts,
    )
    out_path = out_dir / filename

    meta_lines = [
        f"step          : {step}",
        f"session_id    : {session_id}",
        f"session_date  : {session_date}",
        f"model         : {model}",
        f"label         : {label}",
        f"sent_at       : {ts}",
        f"system_chars  : {len(system_prompt):,}",
        f"user_chars    : {len(user_message):,}",
    ]
    if extra_meta:
        for k, v in extra_meta.items():
            meta_lines.append(f"{k:<14}: {v}")

    content = (
        "=== METADATA ===\n"
        + "\n".join(meta_lines)
        + "\n\n=== SYSTEM PROMPT ===\n"
        + system_prompt
        + "\n\n=== USER MESSAGE ===\n"
        + user_message
        + "\n"
    )

    out_path.write_text(content, encoding="utf-8")
    return out_path
